[package]
name = "CIEXYZ"
version = "0.1.0"
edition = "2024"


[dependencies]
eframe = "0.27"
egui = "0.27"
egui_extras = "0.27"
serde = { version = "1.0", features = ["derive"] }
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
rfd = "0.14"
